---
title: "Data Science for Public Policy"
subtitle: "Data Visualization, Quarto, and Git"
author: "Kassandra Martinchek - KM1775"
format: html
editor: visual
---

## Project Introduction

## Data Details

Hyperlink: https://datacatalog.urban.org/dataset/credit-health-during-covid-19-pandemic/resource/0f812245-6b99-4f13-b7e2-e3398a7dc10b 

## Clean and Prepare the Data for Visualization

```{r}

# load in relevant libraries for analysis
library(readxl)
library(tidyverse)
library(stringr)

# load in the data
credit_feb20 <- read_excel("data/covidcredithealth_state.xlsx", sheet = "State 2020_02")

# inspect the data and note that these are character strings because of n/a values
head(credit_feb20)

# rename column names to be snake case for analysis
colnames(credit_feb20) <- c("state", "subprime_a", "subprime_c", "subprime_w", "collections_a", "collections_c", "collections_w", "med_debt_a", "med_debt_c", "med_debt_w", "cred_use_a", "cred_use_c", "cred_use_w", "stud_del_a", "stud_del_c", "stud_del_w", "cred_del_a", "cred_del_c", "cred_del_w", "auto_del_a", "auto_del_c", "auto_del_w", "mort_del_a", "mort_del_c", "mort_del_w", "afs_use_a", "afs_use_c", "afs_use_w", "afs_del_a", "afs_del_c", "afs_del_w", "score_a", "score_c", "score_w", "mmed_a", "mmed_c", "mmed_w", "medical_a", "medical_c", "medical_w")

# replace n/a values in strings
credit_feb20 <- credit_feb20 %>%
  mutate(across(.cols = everything(), .fns = ~str_replace(., "n/a", ""))) 

# remove $ from median debt variables
credit_feb20 <- credit_feb20 %>%
  mutate(med_debt_a = str_remove(string = med_debt_a, pattern = "\\$")) %>%
  mutate(med_debt_c = str_remove(string = med_debt_c, pattern = "\\$")) %>%
  mutate(med_debt_w = str_remove(string = med_debt_w, pattern = "\\$")) %>%
  mutate(mmed_a = str_remove(string = mmed_a, pattern = "\\$")) %>%
  mutate(mmed_c = str_remove(string = mmed_c, pattern = "\\$")) %>%
  mutate(mmed_w = str_remove(string = mmed_w, pattern = "\\$")) 

# make string data numeric
credit_feb20 <- credit_feb20 %>%
  mutate(across(.cols = !state, .fns = ~as.numeric(.))) 
         
```



## Workshopping code below still

```{r}

## get support in adjusting code below

# remove $ signs in median debt variables
credit_feb20 <- credit_feb20 %>%
  mutate(across(.cols = c("med_debt_a", "med_debt_c", "med_debt_w", "mmed_a", "mmed_c", "mmed_w"), .fns = ~str_remove(string = c("med_debt_a", "med_debt_c", "med_debt_w", "mmed_a", "mmed_c", "mmed_w"), pattern = "\\$")))

credit_feb20 <- credit_feb20 %>%
  mutate(across(.cols = everything(), .fns = ~str_remove(string = c("med_debt_a", "med_debt_c", "med_debt_w", "mmed_a", "mmed_c", "mmed_w"), pattern = "\\$")))

credit_feb20 <- credit_feb20 %>%
  mutate(med_debt_a = str_remove(string = med_debt_a, pattern = "\\$"))

         
```



## Visualization 1: Do States with Consumers Who Use More Payday Loans Have More Trouble Repaying Loans?

```{r}

# mapping AFS use against AFS delinquencies

credit_feb20 %>%
  ggplot() +
  geom_point(mapping = aes(x = afs_use_a, y = afs_del_a), color = "red") +
  geom_smooth(method = lm, mapping = aes(x = afs_use_a, y = afs_del_a), color = "blue") +
  labs(
    title = "States With More AFS Use Experience Greater Delinquencies",
    subtitle = "AFS Use and AFS Delinquencies by State, February 2020",
    caption = "Data Source: Kassandra Martinchek, Alex Carther, Breno Braga, Caleb Quakenbush, and Signe-Mary McKernan. 2022. Credit Health during the COVID-19 Pandemic Dataset. Urban Institute. Accessible from https://datacatalog.urban.org/dataset/credit-health-during-covid-19-pandemic",
    x = "Share of Consumers Using AFS",
    y = "Share of Consumers With AFS Delinquencies"
  ) 

         
```




## Visualization 2: Do Communities of Color Have Poorer Credit Than Majority-White Communities in the DMV?

```{r}

# filter data to states in the DMV
 dmv_credit <- credit_feb20 %>%
  filter(state == "DC" | state == "MD" | state == "VA") %>%
  select(state, subprime_a, subprime_c, subprime_w)

# transform data set from wide to long for visualization
 
  viz2 <- pivot_longer(
    data = dmv_credit,
    cols = c(subprime_a, subprime_c, subprime_w),
    names_to = "community",
    values_to = "share"
  )

# recode community variable for visualization
  viz2 <- viz2 %>%
  mutate(community = case_when(community == "subprime_a" ~ "all",
                               community == "subprime_c" ~ "comm col",
                               community == "subprime_w" ~ "white"))

# stacked bar chart for each state
  viz2 %>%
    ggplot(aes(x = state, y = share, fill = community)) +
    geom_bar(position = "dodge", stat = "identity") +
    scale_fill_discrete(name = "Community", labels = c("All Communities", "Communities of Color", "Majority White Communities")) +
    labs(
    title = "Communities of Color in the District Have Poorer Credit Health",
    subtitle = "Share of Consumers with Subprime Credit Scores by Community in Maryland, DC, and Virginia, February 2020",
    caption = "Data Source: Kassandra Martinchek, Alex Carther, Breno Braga, Caleb Quakenbush, and Signe-Mary McKernan. 2022. Credit Health during the COVID-19 Pandemic Dataset. Urban Institute. Accessible from https://datacatalog.urban.org/dataset/credit-health-during-covid-19-pandemic",
    x = "State",
    y = "Share of Consumers With Subprime Credit Scores"
  ) 
    
         
```






